services:
  - type: web
    name: skybook-backend
    runtime: java
    rootDir: skybook-airline-backend
    buildCommand: mvn clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false